# Generated by Django 4.2.5 on 2023-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
